Admin can upload casa_org logo #1088
rubyforgood/casa pull request #1131
Opened 2020-10-19 21:28 UTC by rebecarancan

### What github issue is this PR for, if any?
Resolves #1088

### What changed, and why?
- Installed Active Storage to manage file uploads
- Installed gem image_processing to handle images  easily
- Added a file upload field on Casa Org form
- The logo uploaded will appear in the sidebar

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪
- Added a expectation on CasaOrg model spec to test the attach functionality
- Added a expectation on CasaOrg edit request spec to test if the upload was successful

### Screenshots please :)
**CasaOrg form:**
![Captura de tela de 2020-10-19 18-26-06](https://user-images.githubusercontent.com/42655535/96513516-9740b180-1238-11eb-97a4-c88e4febdf61.png)

**New CasaOrg logo on sidebar:**
![Captura de tela de 2020-10-19 18-26-55](https://user-images.githubusercontent.com/42655535/96513596-b50e1680-1238-11eb-98d7-7060f54b65bc.png)

![Captura de tela de 2020-10-19 18-01-58](https://user-images.githubusercontent.com/42655535/96513287-45982700-1238-11eb-85c4-423d9a682ce5.png)

2020-10-19 22:25 UTC, littleforest requested changes

2020-10-19 22:25 UTC, littleforest commented on app/views/layouts/_sidebar.html.erb
> +      <%= image_tag current_organization.logo.variant(resize_to_limit: [200, 100]) %>
Please keep the `alt` text.

2020-10-19 23:56 UTC, compwron commented
This is looking very very good! 
+1 please put back the alt text and then I think we're ready to merge! :) 💪✨

2020-10-20 00:24 UTC, littleforest commented
@compwron please hold off on merging, I want to have @rebecarancan add one line to the Dockerfile so imagemagick will be installed but wanted to test locally first! 

@rebecarancan thanks for getting this set up!  Also, please fix merge conflicts when you get a chance.

2020-10-20 02:42 UTC, littleforest commented
@rebecarancan could you add imagemagick to [this section](https://github.com/rubyforgood/casa/blob/master/Dockerfile#L31-L37) of the Dockerfile like so:

```
RUN apk update && apk upgrade && apk add --update --no-cache \
  bash \
  imagemagick \
  nodejs \
  postgresql-client \
  tzdata \
  vim \
  yarn && rm -rf /var/cache/apk/*
```

2020-10-20 15:50 UTC, littleforest approved these changes
🎉 💯

2020-10-21 07:18 UTC, merged