Make seed not delete. Remove versions as the last step in seed
rubyforgood/casa pull request #1576
Opened 2021-01-10 20:09 UTC by compwron

### What github issue is this PR for, if any?
https://rubyforgood.slack.com/archives/CVB0QJGVD/p1610257613368700

### What changed, and why?
Make seed not delete. Remove versions as the last step in seed

### How will this affect user permissions?
no

### How is this tested? (please write tests!) 💖💪
run

2021-01-11 01:17 UTC, littleforest requested changes
This is not idempotent if we remove deleting the tables. I'm all for the change you are adding to not delete, but the populators need some love to rewrite `create!` statements to `find_or_create_by`.

2021-01-12 05:22 UTC, merged

2021-01-12 05:22 UTC, compwron commented on db/seeds.rb
> +    log "NOTE: seed does not delete anything anymore! You have to run rake db:seed:replant to truncate and re-seed"
Good point! I updated the readme and made seed not exactly idempotent but at least able to run multiple times without error- by checking existing objects

2021-01-12 05:22 UTC, compwron commented
> This is not idempotent if we remove deleting the tables. I'm all for the change you are adding to not delete, but the populators need some love to rewrite `create!` statements to `find_or_create_by`.

Whups. Fixed, I think. :)

2021-01-12 19:08 UTC, keithrbennett commented
I tried the following:

```
rake db:seed:replant > before && rake db:seed > after && diff before after
```
...and got the following:

```
13c13
<    76  CasaCase
---
>   150  CasaCase
20c20
<    76  CaseAssignment
---
>   152  CaseAssignment
23c23
<   374  CaseContact
---
>   744  CaseContact
```

So I don't think this script has remained idempotent.