[#1739] Add court details to past court dates
rubyforgood/casa pull request #2080
Opened 2021-05-25 19:55 UTC by rhian-cs

### What github issue is this PR for, if any?
Resolves #1759

### What changed, and why?
As requested in #1759, the past court dates now have a page of their own with additional information about the CASA case at the time, such as: judge, hearing type and court mandates.

The link to that page is available at the edit page of a given CASA case.

#### Acceptance Criteria
- [x] Dates are clickable underneath "Past Court Dates" on the Edit CASA Case page.
- [x] Clicking on a date takes you to a page where you can see details associated with that past court date, including:
  - [x] Hearing type
  - [x] Judge
  - [x] Court mandates and implementation status

### How will this affect user permissions?
The permissions to access the past court date page mirror the permissions to edit the associated case.

- Volunteer permissions: Can only see the page if they are associated with the case
- Supervisor permissions: Can only see the page if they are in the same organization as the case
- Admin permissions: Can always see the page

### How is this tested? (please write tests!) 💖💪
#### Automated tests
- Added model and request specs for the past court dates
- Added view specs for the past court date show page
- Modified the system specs for the CASA case edit page to check if the court dates links are actually visible

#### Manual testing
I also had to test if the heroku scheduler task was working, so I modified a CASA case to:
- Have court details
- Have a next court date in the past (so the scheduler task picks it up)

And then I ran the scheduler task.

### Screenshots please :)

#### The CASA case edit page now have links to the past court dates

![01-desktop-edit](https://user-images.githubusercontent.com/72531802/119559626-4fa77880-bd79-11eb-8d3e-644110c2cdaa.png)

#### Past court dates page (desktop)
![02-desktop-show](https://user-images.githubusercontent.com/72531802/119559673-6057ee80-bd79-11eb-9189-58454a3b9ef7.png)

#### Past court dates page (mobile top)
![03-mobile-show](https://user-images.githubusercontent.com/72531802/119559681-61891b80-bd79-11eb-9735-e5c618e42cc2.png)

#### Past court dates page (mobile bottom)
![04-mobile-show](https://user-images.githubusercontent.com/72531802/119559719-6cdc4700-bd79-11eb-85fb-d3fdb5b1d75d.png)

To be honest I'm not a big fan of how the table looks in mobile, but I thought I shouldn't modify the global table style just for this alteration.

2021-05-25 20:16 UTC, Diego-Thomaz approved these changes

2021-05-25 20:18 UTC, compwron commented
Exciting!
@Diego-Thomaz what criteria are you using to review this PR?

2021-05-25 20:27 UTC, compwron requested changes
this is looking great! Please don't merge until I get a chance to look it over in more depth tonight :)

2021-05-26 01:58 UTC, compwron commented
Please fix the failing test :) 
```
Failed examples:

rspec ./spec/requests/past_court_dates_spec.rb:16 # /casa_cases/:casa_case_id/past_court_dates/:id GET /show when the request is authenticated 
```
https://github.com/rubyforgood/casa/pull/2080/checks?check_run_id=2669068108

2021-05-26 02:00 UTC, compwron approved these changes
Very nice! :)

2021-05-26 13:13 UTC, Diego-Thomaz commented
> Exciting!
> @Diego-Thomaz what criteria are you using to review this PR?

Hi @compwron , I'm mentoring @rhian-cs in his open sources. He usually give me context about the issues he's working on, and I review his code to help him.

2021-05-26 14:57 UTC, compwron commented
Very cool :)

2021-05-26 21:11 UTC, rhian-cs commented
> Please fix the failing test :)

My bad, it was working locally so I thought it was just a flake. Disabling bullet for the spec fixed it though.

2021-05-27 02:02 UTC, compwron commented
As per our stakeholder meeting today, we do NOT want to wipe court mandates when a court date passes, because the mandates often stay the same. 

Also on a technical level, it does not yet seem useful to save a snapshot of old court mandates when a court report rolls over to the past. Maybe someday.

2021-05-27 02:10 UTC, compwron commented on spec/policies/past_court_date_policy_spec.rb
> +  permissions :show? do
these are great tests, yay testing permissions :)

2021-05-27 02:13 UTC, compwron commented on spec/requests/past_court_dates_spec.rb
> +RSpec.describe "/casa_cases/:casa_case_id/past_court_dates/:id", :disable_bullet, type: :request do
We need to start un-breaking bullet... we have way too many n+1s 
https://github.com/flyerhzm/bullet

2021-05-27 02:14 UTC, compwron commented on spec/system/casa_cases/edit_spec.rb
> +    let!(:formatted_date_without_details) { I18n.l(past_court_date_without_details.date, format: :full, default: nil) }
I would rather spell this out than reference the yaml- tests don't need to be as DRY as prod code. tests Should not test prod code by running other prod code

2021-05-27 02:15 UTC, compwron approved these changes
Beautiful :)

2021-05-27 02:19 UTC, merged