Adds Request Spec verifying Judge Name in DOCX for past court dates
rubyforgood/casa pull request #2724
Opened 2021-10-10 16:36 UTC by armahillo

### What github issue is this PR for, if any?

Closes #2517

### What changed, and why?
I added two new request specs to past_court_date_spec, similar to the
way they were done in the regular case report request spec. The DOCX
format is really hard to read and most of it is superfluous XML so I
wrote an additional helper method that strips out all the XML and
reveals just the underlying content. This spec was only needing to
verify that a specific content string was present, so it was enough.

That new helper is added alongside the existing (awesome!) helper for
this need.

The request specs themselves test both the affirmative and negative
cases of having a judge or not, since the judge's presence is optional.

ADDITIONAL CLEANUP:
I noticed that the PastCourtDate model had an extraneous presence
validation for the :casa_case_id field. As of Rails 5, belongs_to
implies a required presence for the association key unless you specify
optional: true. I modified the model spec that was verifying the
integrity of this association.

### How will this affect user permissions?
N/A

### How is this tested? (please write tests!) 💖💪
Manual testing to verify the feature worked normally (and also to see what it looked like).

Commit content is essentially just specs, so we're good here!

### Screenshots please :)
N/A

### Feelings gif (optional)
![GREEN LIGHT](https://media.giphy.com/media/bjcrpWZYOPYQZOm2fE/giphy.webp)`

2021-10-10 22:47 UTC, FireLemons approved these changes

2021-10-10 22:49 UTC, FireLemons commented
could you run `bundle exec standardrb --fix` and then commit on this branch?

2021-10-10 22:50 UTC, FireLemons requested changes

2021-10-10 23:27 UTC, compwron approved these changes
Wonderful :)

2021-10-11 04:21 UTC, armahillo commented
ah!! `standardrb`

I ran `rubocop` before pushing and it flagged a bunch of issues so I figured it wasn't being used in CI -- I'll fix this tomorrow, thank you!

2021-10-11 20:48 UTC, merged