Weston 5105 casa group
rubyforgood/casa pull request #5106
Opened 2023-08-09 19:05 UTC by sandfortw

### What github issue is this PR for, if any?
Resolves #5105 

### What changed, and why?
Added a uniqueness constraint for case groups scoped to the casa org they belong to. 

In other words, you now cannot have a case group with the same name within the same casa org. 

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪

Model Validation Spec:

<img width="714" alt="image" src="https://github.com/rubyforgood/casa/assets/80081206/d62a6997-07d7-4654-a092-7a58370a5f51">

System Spec:

<img width="490" alt="image" src="https://github.com/rubyforgood/casa/assets/80081206/df24cc8f-e94b-496f-8105-9aae2c512a60">

### Screenshots please :)

<img width="442" alt="Screenshot 2023-08-09 at 1 02 16 PM" src="https://github.com/rubyforgood/casa/assets/80081206/dd08ebae-7de5-45ec-b73e-6583ea2efa0a">

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`![alt text](https://media.giphy.com/media/1nP7ThJFes5pgXKUNf/giphy.gif)`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

2023-08-09 19:24 UTC, sandfortw commented
I had to update the factory for case_group because it was throwing errors for not creating unique names.

2023-08-11 21:17 UTC, littleforest reviewed
Looks great! Just one minor change request.

2023-08-11 21:17 UTC, littleforest commented on app/models/case_group.rb
> +  validates :name, uniqueness: {scope: :casa_org}
```suggestion
  validates :name, presence: true, uniqueness: {scope: :casa_org}
```

2023-08-12 04:30 UTC, sandfortw commented on app/models/case_group.rb
> +  validates :name, uniqueness: {scope: :casa_org}
Thank you!

2023-08-12 04:31 UTC, sandfortw commented
Committed that change, thanks for the edit!

2023-08-16 00:28 UTC, FireLemons requested changes

2023-08-16 00:28 UTC, FireLemons commented on app/models/case_group.rb
> +  validates :name, presence: true, uniqueness: {scope: :casa_org}
Can you strip whitespace too?

2023-08-29 01:38 UTC, littleforest approved these changes

2023-08-30 00:09 UTC, merged

2023-08-30 00:09 UTC, FireLemons commented
:medal_sports: