Update styles for new case contact form
rubyforgood/casa pull request #5557
Opened 2024-02-28 03:05 UTC by Natblow

### What github issue is this PR for, if any?
Resolves #5498 

### What changed, and why?

- [x]  Update all checkbox and radio button outlines in the unchecked state to be #757575 instead of #E5E5E5
- [x] Right-align form buttons and make them title case
    - [x]    On pages that include the “Save and Continue” button, this button should be the rightmost, and the “Back” button should be 10 pixels to the left
    - [x]   On pages that include the "Submit" button, this button should be the rightmost, and the "Back" button should be 10 pixels to the left
    - [ ]   For the "New court report topic" in the admin portal, "Submit" and "Back" should be right aligned with "Submit" being the rightmost.

- [x] For Mobile view only:
    - [x] Reduce the size of the H1 “Record new case contact” to size H2
    - [x] Reduce the size of the H2 “Contact Details” to size H3

### How will this affect user permissions?
- Volunteer permissions: n/a
- Supervisor permissions: n/a
- Admin permissions: n/a

### How is this tested? (please write tests!) 💖💪

Since this is a style update, we checked in our local development environment that the changes were correctly implemented. Refer to screenshots below

### Screenshots please :)

**Desktop view showing the new outline colour for checkboxes and radio buttons, as well as the aligned buttons**
![screenshot](https://private-user-images.githubusercontent.com/85654561/303021122-c9b1ca8c-36c8-48ec-a4ad-65fd251f11f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODkyMTgsIm5iZiI6MTcwOTA4ODkxOCwicGF0aCI6Ii84NTY1NDU2MS8zMDMwMjExMjItYzliMWNhOGMtMzZjOC00OGVjLWE0YWQtNjVmZDI1MWYxMWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAyNTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MTk5OTJiOGNkNzk5Y2IzYjI3OThhZjlmOTllNDY4YTcyZGMwY2Y0ZDdlYWEzNWMyODM0ZjRiZDU2YmVmNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lkbk2hxjH6ezO6h4m4dFAuaysr0exLZf2Ss3kH0WOhQ)

**Mobile view showing the reduced heading size**
![mobile-screenshot](https://private-user-images.githubusercontent.com/85654561/303021127-df84162c-469a-4078-9a25-133b4e56c5a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODkyMTgsIm5iZiI6MTcwOTA4ODkxOCwicGF0aCI6Ii84NTY1NDU2MS8zMDMwMjExMjctZGY4NDE2MmMtNDY5YS00MDc4LTlhMjUtMTMzYjRlNTZjNWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAyNTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNTI3YmQyYTkyODFkNzE0NzE1NWMxNGQzYzgyOWMyYjlhMjA0OWJiZWMxOGQyYTFhNDQwYWQ5ZjdhNjI3NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.buZKJtuAo4HDR8bPE-6vPEEVfArLS8GLiXRCUmzeRoM)

**Mobile view showing the button layout is per the Figma file provided (different from the desktop view)**
![mobile-screenshot-button-layout](https://private-user-images.githubusercontent.com/85654561/303021129-1eb9b0f8-bacb-4f02-b755-ffc6206dd7f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODkyMTgsIm5iZiI6MTcwOTA4ODkxOCwicGF0aCI6Ii84NTY1NDU2MS8zMDMwMjExMjktMWViOWIwZjgtYmFjYi00ZjAyLWI3NTUtZmZjNjIwNmRkN2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAyNTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzk1NWNhZGI1NmExZDU5ZjExMzc5OWE5NGMxNmFmNWE1YTM4OWM1NjJlYTc5ZmY1OTFmMWQ3MWI1MTA5NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJzozyiK8J0AUFdlxrh7_QH_h7_g60f0eHXWnQFBkqU)

2024-04-14 18:22 UTC, compwron commented
@Natblow please resolve merge conflicts so we can merge :)

2024-04-14 18:22 UTC, compwron commented
I'm sorry that I let this sit so long! :(

2024-04-14 18:24 UTC, compwron commented
I tried to resolve the merge conflicts - let's see how CI goes and fix-forwards if needed.

2024-05-20 19:45 UTC, jp524 commented
I merged `main` again and the CI passes now! Should be good to go @compwron.

2024-05-23 01:22 UTC, elasticspoon requested changes
Hey! Sorry for taking so long to review, really appreciate the work. :heart: 

What you did was great except for a minor fix. Semantically `h1` and `h2` tags mean different things but in our situation we just want to sizes of the items to be different between web and mobile. So instead of changing the size by changing the tag we should keep the tag the same and just style it differently.

2024-05-23 01:22 UTC, elasticspoon commented on app/components/form/title_component.html.erb
> +      <h2 class="case-contacts-form mobile-title"><%= @title %></h2>
I know the issue says to change "H1 to size H2", but we shouldn't change the semantic HTML to achieve that. Keep it is an H1 and just change the size of the text in the @media rule.

2024-05-23 01:22 UTC, elasticspoon commented on app/components/form/title_component.html.erb
> +      <h3 class="col-12 col-md-6 case-contacts-form mobile-title"><%= @subtitle %></h3>
same with these h tags

2024-05-23 21:35 UTC, elasticspoon approved these changes
Thank you!

2024-05-23 21:35 UTC, merged