Disable expenses page when orgs have no expenses #5762
rubyforgood/casa pull request #5793
Opened 2024-05-30 18:45 UTC by iamronakgupta

### What github issue is this PR for, if any?
Resolves #5762 

### What changed, and _why_?
expense step is removed from casa_contact/new when both expenses option is disable.

### How is this **tested**? (please write tests!) 💖💪
_Note: if you see a flake in your test build in github actions, please post in slack #casa "Flaky test: <link to failed build>" :) 💪_
_Note: We love [capybara](https://rubydoc.info/github/teamcapybara/capybara) tests! If you are writing both haml/js and ruby, please try to test your work with tests at every level including system tests like https://github.com/rubyforgood/casa/tree/main/spec/system_ 

### Screenshots please :)
Showing only 2 steps when both expenses option is disabled

### Feelings gif (optional)
_What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:_
`![alt text](https://media.giphy.com/media/1nP7ThJFes5pgXKUNf/giphy.gif)`

2024-05-31 10:31 UTC, elasticspoon reviewed
I have not gotten a chance to look closely at this but a couple of quick comments that I probably should have included in the issue. You might already be doing all these things but in case you aren't:

1. The reason we are doing this is cause of a bug that got fixed with this PR https://github.com/rubyforgood/casa/pull/5708/files. So I don't think that fix was ideal so I would like to fix it more "correctly". Specifically, I would like to undo 
```diff
- params.require(:case_contact).permit(
+ params.fetch(:case_contact, {}).permit(
```
and 
```diff
- params[:case_contact][:status] = step.to_s if !@case_contact.active?
+ params[:case_contact][:status] = step.to_s if !@case_contact.active? && params.key?(:case_contact)
```
by making sure the case contact is always getting passed in.

2. The Save and Continue button should change to Submit on the second step if there is not third step

Also I don't remember off the top of my head so hopefully you can tell me. When the case contacts get submitted this way
```rb
#case_contacts/form_controller.rb
    if @case_contact.update(case_contact_params)
      respond_to do |format|
        format.html {
          if step == steps.last
            finish_editing
          else
            render_wizard @case_contact, {}, {case_contact_id: @case_contact.id}
          end
        }
        format.json { head :ok }
      end
```
does `finish_editing` actually fire off?

2024-05-31 20:07 UTC, iamronakgupta commented
> ```diff
> params.fetch(:case_contact, {}).permit(
> ```

@elasticspoon yes `finish_editing` is called.

2024-05-31 20:55 UTC, iamronakgupta commented
> I have not gotten a chance to look closely at this but a couple of quick comments that I probably should have included in the issue. You might already be doing all these things but in case you aren't:
> 
> 1. The reason we are doing this is cause of a bug that got fixed with this PR https://github.com/rubyforgood/casa/pull/5708/files. So I don't think that fix was ideal so I would like to fix it more "correctly". Specifically, I would like to undo
> 
> ```diff
> - params.require(:case_contact).permit(
> + params.fetch(:case_contact, {}).permit(
> ```
> 
> and
> 
> ```diff
> - params[:case_contact][:status] = step.to_s if !@case_contact.active?
> + params[:case_contact][:status] = step.to_s if !@case_contact.active? && params.key?(:case_contact)
> ```
> 
> by making sure the case contact is always getting passed in.
> 
> 2. The Save and Continue button should change to Submit on the second step if there is not third step
> 
> Also I don't remember off the top of my head so hopefully you can tell me. When the case contacts get submitted this way
> 
> ```ruby
> #case_contacts/form_controller.rb
>     if @case_contact.update(case_contact_params)
>       respond_to do |format|
>         format.html {
>           if step == steps.last
>             finish_editing
>           else
>             render_wizard @case_contact, {}, {case_contact_id: @case_contact.id}
>           end
>         }
>         format.json { head :ok }
>       end
> ```
> 
> does `finish_editing` actually fire off?

For Point 1: This has been reverted back as we will not be rendering expenses screen so contact_case params will not crashes
For point 2: 'Save and Continue' will be replaced with 'Submit' button when both expenses are disabled and notes is the last stel

2024-06-01 10:58 UTC, schoork requested changes

2024-06-01 10:58 UTC, schoork commented on app/models/case_contact.rb
> +  def form_steps
If we're gonna do this pattern, then let's future proof the app a bit. There are a few calls to `CaseContact::FORM_STEPS` in the app. Replace those with this method.

1. `CaseContactsController:58`
2. `CaseContactsController:65`
3. `CaseContact:38`

2024-06-01 10:58 UTC, schoork commented on app/models/case_contact.rb
> +    steps.delete(:expenses) unless creator.casa_org.additional_expenses_enabled || creator.casa_org.show_driving_reimbursement
Unless with OR is tough to understand. Can we extract these two into a method that returns true or false?
```
creator.casa_org.additional_expenses_enabled
creator.casa_org.show_driving_reimbursement
```

2024-06-01 10:58 UTC, schoork commented on app/views/case_contacts/form/notes.html.erb
> +          <% end %>
Ripe for a ViewComponent in the `Form` namespace if you're feeling ambitious.

2024-06-04 20:32 UTC, elasticspoon commented on app/views/case_contacts/form/notes.html.erb
> +          <%= render(Form::SubmitButtonComponent.new(last_step: @case_contact.form_steps.last, current_step: :notes)) %>
If we are going to move the button into a component the component should encapsulate the whole button not just the contents of the button. That is the `button_tag` should be included in the component.

2024-06-04 20:34 UTC, elasticspoon commented on app/components/form/submit_button_component.rb
> +    end
This conditional should be it's own method. Probably something like `submit_text` or `button_text`

2024-06-06 18:51 UTC, iamronakgupta commented
I am not getting why `submit_button_component.html.erb` is failing for erblint

2024-06-06 20:50 UTC, elasticspoon commented
try copy pasting these. or check this commit https://github.com/elasticspoon/casa/commit/885c41125d853cd69f8ea8b3df29bff8d3ad92b1


```rb
# frozen_string_literal: true

class Form::SubmitButtonComponent < ViewComponent::Base
  def initialize(last_step:, current_step:)
    @text = submit_button_text(last_step:, current_step:)
  end

  def submit_button_text(last_step:, current_step:)
    return "Submit" if last_step == current_step

    "Save and Continue"
  end
end

```

```rb
# frozen_string_literal: true

require "rails_helper"

RSpec.describe Form::SubmitButtonComponent, type: :component do
  before(:each) do
    render_inline(described_class.new(last_step:, current_step:))
  end

  context "when last step is equal to current step" do
    let(:last_step) { :notes }
    let(:current_step) { :notes }
    it "renders Submit button" do
      expect(page).to have_content("Submit")
    end
  end

  context "when last step is not equal to current step" do
    let(:last_step) { :notes }
    let(:current_step) { :expenses }
    it "renders Save and continue button" do
      expect(page).to have_content("Save and Continue")
    end
  end
end
```

```erb
<%= button_tag type: "submit", class: "btn-sm main-btn primary-btn btn-hover" do %><i class="lni lni-checkmark-circle mr-5"></i><%= @text %><% end %>
```
and I have no clue why erb-lint is unhappy. The button looks like it should work fine.

2024-06-06 22:02 UTC, iamronakgupta commented
> try copy pasting these. or check this commit [elasticspoon@885c411](https://github.com/elasticspoon/casa/commit/885c41125d853cd69f8ea8b3df29bff8d3ad92b1)
> 
> ```ruby
> # frozen_string_literal: true
> 
> class Form::SubmitButtonComponent < ViewComponent::Base
>   def initialize(last_step:, current_step:)
>     @text = submit_button_text(last_step:, current_step:)
>   end
> 
>   def submit_button_text(last_step:, current_step:)
>     return "Submit" if last_step == current_step
> 
>     "Save and Continue"
>   end
> end
> ```
> 
> ```ruby
> # frozen_string_literal: true
> 
> require "rails_helper"
> 
> RSpec.describe Form::SubmitButtonComponent, type: :component do
>   before(:each) do
>     render_inline(described_class.new(last_step:, current_step:))
>   end
> 
>   context "when last step is equal to current step" do
>     let(:last_step) { :notes }
>     let(:current_step) { :notes }
>     it "renders Submit button" do
>       expect(page).to have_content("Submit")
>     end
>   end
> 
>   context "when last step is not equal to current step" do
>     let(:last_step) { :notes }
>     let(:current_step) { :expenses }
>     it "renders Save and continue button" do
>       expect(page).to have_content("Save and Continue")
>     end
>   end
> end
> ```
> 
> ```
> <%= button_tag type: "submit", class: "btn-sm main-btn primary-btn btn-hover" do %><i class="lni lni-checkmark-circle mr-5"></i><%= @text %><% end %>
> ```
> 
> and I have no clue why erb-lint is unhappy. The button looks like it should work fine.

every other issues got resolved but erb-lint is still unhappy with submit_button_component, its telling there is extra whitespace i can't detect any

2024-06-07 04:36 UTC, elasticspoon approved these changes
@iamronakgupta I fixed the linting issues.

Thanks so much for the work! Overall it looks good to me! 

Couple minor nits but nothing blocking. Feel free to tackle the nits or don't. I am fine merging as is:
- the comment about the view component
- since you made the submit button component you might as well replace the buttons in the other views with is as well.

2024-06-07 04:36 UTC, elasticspoon commented on app/components/form/submit_button_component.rb
Nit - I think the "idiomatic" way to write this would be:

```rb
class Form::SubmitButtonComponent < ViewComponent::Base
  def initialize(last_step:, current_step:)
    @last_step = last_step
    @current_step = current_step
  end

  def button_text
    return "Submit" if @last_step == @current_step
    "Save and Continue"
  end
end
```

2024-06-07 14:27 UTC, iamronakgupta commented on app/components/form/submit_button_component.rb
I can create a separate PR for optimization or you want me to complete in this only?

2024-06-07 14:36 UTC, elasticspoon commented on app/components/form/submit_button_component.rb
Separate PR is fine by me. Lemme know if you want me to open an issue for it.

2024-06-07 16:24 UTC, iamronakgupta commented on app/components/form/submit_button_component.rb
I think New issue would be better. 
You can list all the required changes there.

2024-06-09 12:51 UTC, schoork commented on app/components/form/submit_button_component.rb
Is the a return guard better over ternary here?
```
def button_text
  @last_step == @current_step ? "Submit" : "Save and Continue"
end
```

2024-06-09 12:51 UTC, schoork approved these changes

2024-06-09 17:08 UTC, merged

2024-06-09 17:10 UTC, elasticspoon commented
@iamronakgupta https://github.com/rubyforgood/casa/issues/5819#issue-2342385925 followup issue if you want it