Fix test failures related to time
rubyforgood/casa pull request #5803
Opened 2024-06-01 15:34 UTC by freestylebit

### What github issue is this PR for, if any?

### What changed, and _why_?
On June 1, I ran into some test failures unrelated to the PRs I was working on.  Considering it's June 1, I decided to set the time to the previous month to emulate the same working conditions we had yesterday.

### How is this **tested**? (please write tests!) 💖💪
_Note: if you see a flake in your test build in github actions, please post in slack #casa "Flaky test: <link to failed build>" :) 💪_
_Note: We love [capybara](https://rubydoc.info/github/teamcapybara/capybara) tests! If you are writing both haml/js and ruby, please try to test your work with tests at every level including system tests like https://github.com/rubyforgood/casa/tree/main/spec/system_ 

### Screenshots please :)
_Run your local server and take a screenshot of your work! Try to include the URL of the page as well as the contents of the page._ 

### Feelings gif (optional)
_What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:_
`![alt text](https://media.giphy.com/media/1nP7ThJFes5pgXKUNf/giphy.gif)`

2024-06-01 19:15 UTC, elasticspoon requested changes
Currently health is always gonna break on the first of the month because of 

https://github.com/rubyforgood/casa/blob/504af6943cbd34fe9564df7f621a33fc6f6369f6/app/controllers/health_controller.rb#L24

Idk what the best fix is

2024-06-01 20:35 UTC, albertchae commented
> first_day_of_last_12_months = (12.months.ago.to_date..Date.current).select { |date| date.day == 1 }.map { |date| date.beginning_of_month }

On the first of the month, do we want to include the current day? What if we refactor this to
What if we refactor this to

```ruby
today = Date.current
(0..11).map{|i| (today - i.month).beginning_of_month}
```

2024-06-01 23:45 UTC, compwron commented
+1 to https://github.com/rubyforgood/casa/pull/5803#issuecomment-2143579144 but feel free to merge for now to unblock other builds

2024-06-01 23:45 UTC, compwron approved these changes

2024-06-02 13:11 UTC, freestylebit commented
For this PR, we decided to grab the last 12 months excluding 13 months ago.  We want to emphasize this logic more in case we want to change this behavior in the future (but we now have tests to document this phenomenon).

2024-06-02 13:22 UTC, elasticspoon approved these changes

2024-06-02 13:22 UTC, merged