Ticket 4123 standard court orders btn
rubyforgood/casa pull request #5805
Opened 2024-06-01 19:06 UTC by dalmaboros

### What github issue is this PR for, if any?
Resolves #4123 

### What changed, and _why_?

### How is this **tested**? (please write tests!) 💖💪
_Note: if you see a flake in your test build in github actions, please post in slack #casa "Flaky test: <link to failed build>" :) 💪_
_Note: We love [capybara](https://rubydoc.info/github/teamcapybara/capybara) tests! If you are writing both haml/js and ruby, please try to test your work with tests at every level including system tests like https://github.com/rubyforgood/casa/tree/main/spec/system_ 

### Screenshots please :)
_Run your local server and take a screenshot of your work! Try to include the URL of the page as well as the contents of the page._ 

### Feelings gif (optional)
_What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:_
`![alt text](https://media.giphy.com/media/1nP7ThJFes5pgXKUNf/giphy.gif)`

2024-06-02 18:35 UTC, schoork requested changes

2024-06-03 23:05 UTC, elasticspoon commented on app/javascript/controllers/extended_nested_form_controller.js
> +  addCourtOrder (e) {
`addCourtOrder` could be `add`.

But I'm a bit confused by this controller. `extended-nested-form` implies to be that the behavior should be pretty generic but all the extensions made to the stimulus nest form controller seem very court report focused.

I initially thought based on the name it was being using in more places than with just court orders. I feel like either it should have a generic name `extended-nested-controller` and specific methods specific to court orders removeCourtOrder or have a more specific name `court-order-controller` and more generic method names.

2024-06-03 23:50 UTC, compwron commented on app/javascript/controllers/extended_nested_form_controller.js
> +  addCourtOrder (e) {
I like the longer name "addCourtOrder" tbh, for searchability - but I haven't looked deeply

2024-06-03 23:51 UTC, compwron commented on app/models/case_court_order.rb
> +    "Individual therapy for the Respondent",
Please alphabetize?

2024-06-09 12:23 UTC, schoork approved these changes
Yeah, I do like the changes to this controller, including the name. Good work @dalmaboros!

2024-06-09 17:12 UTC, merged

2024-06-09 17:13 UTC, elasticspoon commented
:partying_face: