Add "Enable Other Duties" as Organization Feature
rubyforgood/casa pull request #5827
Opened 2024-06-10 12:43 UTC by iamronakgupta

### What github issue is this PR for, if any?
Resolves #5771

### What changed, and _why_?
Because not all orgs will use "Other Duties"  added this as a Organization Feature. The default should be "On" (check marked). Titled as "Enable Other Duties"

### How is this **tested**? (please write tests!) 💖💪
_Note: if you see a flake in your test build in github actions, please post in slack #casa "Flaky test: <link to failed build>" :) 💪_
_Note: We love [capybara](https://rubydoc.info/github/teamcapybara/capybara) tests! If you are writing both haml/js and ruby, please try to test your work with tests at every level including system tests like https://github.com/rubyforgood/casa/tree/main/spec/system_ 

### Screenshots please :)
![image](https://github.com/rubyforgood/casa/assets/75837235/c6fdc0d0-079c-4bcb-a0f3-53fec8fda47b)

### Feelings gif (optional)
_What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:_
`![alt text](https://media.giphy.com/media/1nP7ThJFes5pgXKUNf/giphy.gif)`

2024-06-10 14:39 UTC, iamronakgupta commented
Why do we have two same line of code for `Other Duties` in sidebar? 
At [26](https://github.com/rubyforgood/casa/blob/df45fedefa1c6025c4e127a7f00d7b6ade8a4f7e/app/views/layouts/_sidebar.html.erb#L26C11-L26C184) and [43](https://github.com/rubyforgood/casa/blob/df45fedefa1c6025c4e127a7f00d7b6ade8a4f7e/app/views/layouts/_sidebar.html.erb#L43C62-L43C63)

2024-06-10 14:44 UTC, compwron commented
> Why do we have two same line of code for `Other Duties` in app/views/layouts/_sidebar.html.erb? At [26](https://github.com/rubyforgood/casa/blob/df45fedefa1c6025c4e127a7f00d7b6ade8a4f7e/app/views/layouts/_sidebar.html.erb#L26C11-L26C184) and [43](https://github.com/rubyforgood/casa/blob/df45fedefa1c6025c4e127a7f00d7b6ade8a4f7e/app/views/layouts/_sidebar.html.erb#L43C62-L43C63)

The difference appears to be in the `render_check`

2024-06-12 23:03 UTC, elasticspoon requested changes
Looks good overall but there are a few tests that I would like to see added. Thanks :slightly_smiling_face:

2024-06-12 23:03 UTC, elasticspoon commented on app/views/layouts/_sidebar.html.erb
we should add the relevant tests for this sidebar to `spec/views/layouts/sidebar.html.erb_spec.rb`

2024-06-13 21:07 UTC, iamronakgupta commented on app/views/layouts/_sidebar.html.erb
> +          <%= render(Sidebar::LinkComponent.new(title: "Other Duties", icon: "agenda", path: other_duties_path, render_check: current_user.casa_admin? || (current_user.supervisor? && policy(OtherDuty
Oh okay, I missed this. Thank you

2024-06-17 17:39 UTC, iamronakgupta commented
@elasticspoon Can you please help me figure out why this test case is failing?

2024-06-18 00:40 UTC, elasticspoon commented
@iamronakgupta don't worry about it, unfortunately the parallel tests are still "experimental" so are prone to flakiness. Your tests pass the main rspec suite which is what matters.

2024-06-18 01:28 UTC, iamronakgupta commented
> @iamronakgupta don't worry about it, unfortunately the parallel tests are still "experimental" so are prone to flakiness. Your tests pass the main rspec suite which is what matters.

Got it. 
I think I am done with my work on this PR. Can you please review it.

2024-06-19 00:55 UTC, FireLemons requested changes

2024-06-19 00:55 UTC, FireLemons commented on spec/policies/other_duty_policy_spec.rb
> +      it "not allows casa_admins" do
remove "not" before allows for these 3 tests

2024-06-19 00:55 UTC, FireLemons commented on app/views/layouts/_sidebar.html.erb
> +          <%= render(Sidebar::LinkComponent.new(title: "Other Duties", icon: "agenda", path: other_duties_path, render_check: (current_user.casa_admin? || current_user.supervisor?) && policy(OtherDut
Only need 1
```erb
<%= render(Sidebar::LinkComponent.new(title: "Other Duties", icon: "agenda", path: other_duties_path, render_check: policy(OtherDuty).index?)) %>
```

2024-06-19 01:40 UTC, FireLemons approved these changes

2024-06-19 02:47 UTC, merged

2024-06-19 02:48 UTC, FireLemons commented
:medal_sports: