Update README.md
rubyforgood/casa pull request #5877
Opened 2024-07-02 17:43 UTC by MclPio

### What changed, and _why_?
README.md. Add instructions to alter .env file to match developer's  PostgreSQL login credentials.

### How is this **tested**? (please write tests!) 💖💪
No tests ran as this is minor update to README.md

### Feelings gif (optional)
_What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:_
`!['1 minute of work'](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDE2amIwZjZseXRraGpxeWJodGgzcHp6d3FnbWgwZTkyYmtpanZhNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/MW36NXIPuLhgyXhbQt/giphy.gif)`

2024-07-02 18:27 UTC, elasticspoon requested changes

2024-07-02 18:27 UTC, elasticspoon commented on README.md
> +1. Alter `POSTGRES_USER` and `POSTGRES_PASSWORD` in the newly generated `.env` file.
The most common flow is that the `.env` file is generate silently, everything works and you are none the wiser.

Sometimes, like this you the default credentials don't work so a user needs to update the `.env`.

Thus, we should highlight the changing `.env` is more of a trouble shooting set and should only need to be done if `bin/setup` fails with a credentials error.

If that does happen the user should also run `bin/setup` again after fixing the `.env` file

2024-07-03 00:38 UTC, MclPio commented
@elasticspoon I made the changes, moved it to Common issues subsection to be more of a troubleshooting step.

2024-07-03 13:58 UTC, compwron approved these changes
:) https://rubyforgood.slack.com/archives/CVB0QJGVD/p1719719148624109

2024-07-03 13:59 UTC, merged